language: node_js

node_js:
  - 11
  - 10
  - 8

script:
  - npm run test:prod && npm run build

jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - npm run test:prod
        - npm run report-coverage
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: next
